- name: variables to print
  hosts: web
  variables:
    course: "Devops with AWS"
    Duration: "120HRS"
    Trainer: "Sivakumar Reddy M"
  tasks: 
  - name: print the info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Duration is: {{Duration}}, {{Trainer}}"

