- name: variables to print
  hosts: web
  vars: #play level, like global variables
    course: "Devops with AWS"
    duration: "120HRS"
    trainer: "Sivakumar Reddy M"
  tasks: 
  - name: print the info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Duration is: {{duration}}, Trainer: {{Trainer}}"

  - name: print the info again
    vars: #task level variables, same like local variables
      course: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Duration is: {{Duration}}, Trainer: {{Trainer}}"

  - name: print the info again and again
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Duration is: {{Duration}}, Trainer: {{Trainer}}"

