- name: cmd vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt #log in to the server and execute command where as command module cannot able to do this